version: "3"

services:    
  mysql:
    build: 
      dockerfile: ./docker/mysql.dockerfile
      context: .
    image: mysql:8.0  
    container_name: mysql
    ports: 
      - "6612:6612"
    # networks: 
    #   - xxxxx-xxxxxxx
    command: 
      --lower_case_table_names=0     
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: appdb
        MYSQL_USER: phaael
        MYSQL_PASSWORD: 123456
  
  app:
      restart: always
      build:
        dockerfile: ./docker/app.dockerfile
        context: . 
      ports: 
          - 8080:8080
